### PR TITLE
[MaterialTimePicker] updated documentation

### PR DESCRIPTION
**Pull request by kafri8889**
#### Don't forget:

- [x] Identify the component the PR relates to in brackets in the title.
  `[Buttons] Updated documentation`
- [x] Link to GitHub issues it solves. `closes #1234`
- [x] Sign the CLA bot. You can do this once the pull request is opened.

[Contributing](https://github.com/material-components/material-components-android/blob/master/docs/contributing.md)
has more information and tips for a great pull request.

### CODE REVIEW

**Comment by kafri8889** [comment]
change `.setTitle()` to `.setTitleText()`

**Comment by paulfthomas** [comment]
Can you please sign the CLA?

**Comment by kafri8889** [comment]
okay, already

**Comment by paulfthomas** [comment]
Hi, could you rebase your PR? Thanks!

**Pull request closed without merging**
