### PR TITLE
[TextInputLayout] Added option to have prefix-suffix always visible

### LINKED ISSUE #1459: Suffix/prefix for TextInputLayout is visible only when the view is focused
One last thing: The suffix/prefix will only be visible when the view is focused 😉

_Originally posted by @kroegerama in https://github.com/material-components/material-components-android/issues/1427#issuecomment-647332783_

Is it possible to somehow change this behavior? 
My use case is: in the text input for phone number I'm displaying area code as a prefix.
It would be nice if the area code is visible all the time, regardles of the current focus.

### PR DESCRIPTION
**Pull request by gabrielemariotti**
It closes #1459 

Currently the suffix/prefix view is visible only when the `EditText` is focused.
With this change it is possible to set prefix and/or suffix always visible.
The PR preserves the current behavior as default (`prefixAlwaysVisible` and `suffixAlwaysVisible` = `false`).

Updated also the catalog with an example.

Schermata 2020-08-20 alle 01 07 43

### CODE REVIEW

**Comment by SalihCanBinboga** [comment]
When will it merge ?

**Comment by leticiarossi** [comment]
This can now be achieved with the attribute introduced in https://github.com/material-components/material-components-android/commit/22973ff10305397bfc72fed41684175fee8aeefb so will close this PR!

**Comment by Luck-Man** [comment]
How can I achieve the one with suffix AND icon?
I tested it like this and it didn't work:
```
...
app:endIconMode="clear_text"
app:expandedHintEnabled="false"
app:suffixText="meters"
...
```

**Comment by dsn5ft** [comment]
@Luck-Man can you describe what didn't work and send a screenshot?

**Comment by Luck-Man** [comment]
Yes.
I want to use suffix and clear text icon at the same time, like the example shown by @gabrielemariotti:
90699774-71bd1900-e284-11ea-8dd6-5135f2137ea3
But when I tested it, only the suffix is displayed, the trailing icon (clear text icon) didn't. I'm using 1.3.0-alpha03 and I tried it on both filled and outlined types.
Screenshot_1603431063

Here's the layout XML:
```
<com.google.android.material.textfield.TextInputLayout
        android:layout_width="200dp"
        android:layout_height="wrap_content"
        android:hint="@string/length"
        app:endIconMode="clear_text"
        app:expandedHintEnabled="false"
        app:suffixText="@string/meters">
        
        <com.google.android.material.textfield.TextInputEditText
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:inputType="numberDecimal" />
    </com.google.android.material.textfield.TextInputLayout>
    
    <com.google.android.material.textfield.TextInputLayout
        style="@style/MyInputLayout"
        android:layout_width="200dp"
        android:layout_height="wrap_content"
        android:layout_marginTop="20dp"
        android:hint="@string/width"
        app:endIconMode="clear_text"
        app:expandedHintEnabled="false"
        app:suffixText="@string/meters">
        
        <com.google.android.material.textfield.TextInputEditText
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:inputType="numberDecimal" />
    </com.google.android.material.textfield.TextInputLayout>
```

Am I missing something?

**Comment by dsn5ft** [comment]
Interesting! Can you file a separate bug for this with all the information you have?

Also, does the problem only happen when the text fields are smaller width like in your GIF? Does it happen if you make their width match_parent to fill the screen?

**Comment by Luck-Man** [comment]
Yes, it happens if the width is set to `match_parent` as well.

material design text field - suffix   end icon bug

**Pull request closed without merging**
