### PR TITLE
[MaterialDatePicker] Don't clip the background when there's a selected range of dates

### PR DESCRIPTION
**Pull request by rubensousa**
Partially addresses #762 

| Before | After |
| ------------- | ------------- |
| clipped  | unclipped  |

I'm not sure if this should be done for tablets or landscape mode, but according to the spec, the layout should look like this:

image

### CODE REVIEW

**Comment by rubensousa** [comment]
@googlebot I signed it!

**Comment by wcshi** [comment]
Design guidance for desktop / landscape advise drawing the range contained to the calendar region (existing behavior).

**Comment by rubensousa** [comment]
@wcshi CanI close this then?

**Comment by wcshi** [comment]
@rubensousa yes, please close, thank you for your interesting in contributing to the library.

**Pull request closed without merging**
