### PR TITLE
[MaterialContainerTransform] Add support for predictive back

### PR DESCRIPTION
**Pull request by Pittvandewitt**
closes https://github.com/material-components/material-components-android/issues/4112
closes https://github.com/material-components/material-components-android/issues/4042
closes https://github.com/material-components/material-components-android/issues/3619

### CODE REVIEW

**Comment by drchen** [comment]
Hunter, can you take a look?

**Comment by hunterstich** [comment]
Hey @Pittvandewitt,

Going ahead and closing this since it will be fixed by the Fragment library (see https://github.com/material-components/material-components-android/issues/4112#issuecomment-2029834172).  Thanks for raising the issue and PR!

**Comment by Pittvandewitt** [comment]
> Hey @Pittvandewitt,
> 
> Going ahead and closing this since it will be fixed by the Fragment library (see [#4112 (comment)](https://github.com/material-components/material-components-android/issues/4112#issuecomment-2029834172)). Thanks for raising the issue and PR!

Hi @hunterstich, this PR is not just about the crash I reported. It adds predictive back support to the MaterialContainerTransform transition specifically. Would you please reconsider reviewing the PR?

**Comment by Pittvandewitt** [comment]
> Hey @Pittvandewitt,
> 
> Going ahead and closing this since it will be fixed by the Fragment library (see [#4112 (comment)](https://github.com/material-components/material-components-android/issues/4112#issuecomment-2029834172)). Thanks for raising the issue and PR!

Hi @hunterstich, I tried the changes from the Fragment team, but the transition is still not seekable without the changes made in this PR. Could you please reconsider reviewing?

**Comment by Pittvandewitt** [comment]
@hunterstich Please consider reopening this PR. The linked issues are still not fixed.

**Pull request closed without merging**
