### PR TITLE
[MaterialButton] Added IconOnly style

### PR DESCRIPTION
**Pull request by gabrielemariotti**
It covers the point 2. of #1283.

Added
- `Widget.MaterialComponents.Button.IconOnly`
- `Widget.MaterialComponents.Button.UnelevatedButton.IconOnly`
- `Widget.MaterialComponents.Button.OutlinedButton.IconOnly`
- `Widget.MaterialComponents.Button.TextButton.IconOnly`

Updated the catalog demo:
Schermata 2020-09-06 alle 20 00 03
Schermata 2020-09-06 alle 20 00 20

### CODE REVIEW

**Comment by bohsen** [comment]
@hunterstich @raajkumars Friendly bump.
Any chance this will get merged soon?

**Comment by paktalin** [comment]
Is there any progress on it?

**Comment by Surkhojb** [comment]
any update?

**Comment by raajkumars** [comment]
Thanks for this pull request. We were waiting on design input. The style for Material Icon Button has already made it into the release. Please use Wiget.Material2.Button.IconButton style to create icon only button. We will be adding more style to cover  other related styles such as icon buttons with outline.

**Comment by juandiana** [comment]
@raajkumars For Material2, I guess there's no plan on adding an IconButton style, right?

**Pull request closed without merging**
