### PR TITLE
[Documentation] Fix component override documentation

### PR DESCRIPTION
**Pull request by sebastienrouif**
#### Don't forget:

- [x] Identify the component the PR relates to in brackets in the title.
  `[Buttons] Updated documentation`
- [ ] Link to GitHub issues it solves.
- [x] Sign the CLA bot. You can do this once the pull request is opened.

[Contributing](https://github.com/material-components/material-components/blob/develop/CONTRIBUTING.md#pull-requests)
has more information and tips for a great pull request.

### CODE REVIEW

**Comment by sebastienrouif** [comment]
I signed it !

**Comment by ymarian** [comment]
The example says:
"Let's say you wanted to modify `MaterialCardView` so that it uses 16dp rounded"

So the snippet seems correct

**Comment by sebastienrouif** [comment]
@ymarian , the example says "Let's say cards in your theme have 16dp rounded corners, but there's one card that should have 16dp cut corners." and the modify documentation is about making those cut corners theme overlay.

**Comment by maxtracking** [comment]
@ymarian I wonder why this PR is rejected and closed. From the changed files, it clearly follows the description of the use-case - we have rounded corners for all cards in the app BUT the one for which PR sets dedicated style, CUT one. 
```    
was : app:shapeAppearanceOverlay="@style/ShapeAppearanceOverlay.MyApp.MaterialCardView.Rounded">
new: app:shapeAppearanceOverlay="@style/ShapeAppearanceOverlay.MyApp.MaterialCardView.Cut">
```

**Comment by CmoaToto** [comment]
@ymarian I agree with @sebastienrouif and @maxtracking. This PR seems valid and should be reopened.

**Comment by EvoWizz** [comment]
Hello @cketcham,

This issue was closed without any **real** review. 

This change was requested to match the example explained right above the changes. The explanation states that a `cut` corner was expected (See [L211-L213](https://github.com/material-components/material-components-android/pull/393/commits/f8d03ad3acfc3bf77fa54b1a0b4367e8a90f9928#diff-1458e770fab8c11a2af2d7352407128eL211-L213)):

```
Let's say cards in your theme have 16dp rounded corners, but there's one card
that should have 16dp cut corners. To change that card's `cornerFamily`, you can
set the `shapeAppearanceOverlay` attribute on the card in your layout.
```

However, the original version of this file shows a `rounded` corner family and not a `cut` corner family as expected; which can confuse the readers (See [L219-L220](https://github.com/material-components/material-components-android/pull/393/commits/f8d03ad3acfc3bf77fa54b1a0b4367e8a90f9928#diff-1458e770fab8c11a2af2d7352407128eL219-L220)):

```
<style name="ShapeAppearanceOverlay.MyApp.MaterialCardView.Rounded" parent="">
<item name="cornerFamily">rounded</item>
```
Which is why this pull request changes the corner family from `rounded` to `cut` (See [R219-R220](https://github.com/material-components/material-components-android/pull/393/commits/f8d03ad3acfc3bf77fa54b1a0b4367e8a90f9928#diff-1458e770fab8c11a2af2d7352407128eR219-R220)):

```
<style name="ShapeAppearanceOverlay.MyApp.MaterialCardView.Cut">
<item name="cornerFamily">cut</item>
```

The exact same reason applies to all other changes within this documentation in this pull request. The purpose of this pull request is to avoid confusion between multiple types of corners to readers and is also meant for consistency within your docs.

Please take the time to finally correctly review this change.

**Pull request closed without merging**
