### PR TITLE
Kind of fix Travis build

### PR DESCRIPTION
**Pull request by SUPERCILEX**
This PR gets licenses and all of that working, but there are a bunch of compile errors because this lib is completely broken when it comes to the Gradle build. 😕

### CODE REVIEW

**Comment by dsn5ft** [comment]
Thanks for taking a look into this! The license and Gradle build issues (from the command line) have since been resolved.

**Comment by SUPERCILEX** [comment]
Can you take a look at #55 then?

**Comment by dsn5ft** [comment]
The specific failures in #55 have been resolved. We will be looking into why our Espresso tests fail on Travis CI so we can the build back to green (they do pass locally from the command line).

**Comment by SUPERCILEX** [comment]
@dsn5ft was a big fox PR for the library, are you saying it was fixed?

**Comment by dsn5ft** [comment]
Ah I thought you were referring to the Travis CI license issues that caused that PR to fail. Will look into resolving that bottom sheet issues as well.

**Comment by SUPERCILEX** [comment]
Sweet, the PR was approved on Gerrit so it should be good to go—I was told to put it on GitHub.

**Pull request closed without merging**
