### PR TITLE
[DatePicker] Make datepicker fullscreen

### LINKED ISSUE #3956: [DatePicker] date input button and close button can not be used
**Description:**
Screenshot_20231226_111012
The date input button and the close button can be used.
Screenshot_20231226_111026
The date input button can not be used.
Screenshot_20240106_193957
The close button can not be used.

**Expected behavior:** The date input button and the close button can be used.
Screenshot_20240918_232649
Screenshot_20240918_232140
Screenshot_20240918_232213

**Minimal sample app repro:** Catalog app (DatePickerMainDemoFragment)

**Android API version:** 34

**Material Library version:** 1.12.0-alpha02

**Device:** Emulator 32.1.15 (API 32)

### PR DESCRIPTION
**Pull request by manabu-nakamura**
closes #3956

### CODE REVIEW

**Comment by raajkumars** [comment]
@manabu-nakamura Thanks for the PR. But can you explain why the date picker must be made to occupy fullscreen always? For ex: if the date picker is shown on a large screen tablet, then we would not want it to occupy the entire screen.

**Comment by manabu-nakamura** [comment]
(before) The fullscreen datepicker is not fullscreen (edge-to-edge) in 2 & 3-button navigation mode.
292883762-fb14bee4-06c0-42a2-a631-01a44aee9db3
292883786-44e566ff-8abc-4af0-8eae-2bb354850726
294677855-01ec476d-8bd1-43de-8844-e86f29bfc3bb
(after)
292883815-abec546f-acb7-4197-854e-4dee933174f0
292883825-4905ee67-2fb7-4eac-969c-08734e923c07
294677869-8dda01a4-9d70-4a6b-8565-9e3c558988b6

**Review by raajkumars — APPROVED** [review]
LGTM

**Comment by leticiarossi** [comment]
Same reply as in https://github.com/material-components/material-components-android/pull/4285#issuecomment-2353932505 - there's a fix on the way to close https://github.com/material-components/material-components-android/issues/3956!

**Pull request closed without merging**
