### PR TITLE
Revert "[BottomSheetDialogFragment] Added constructor that takes a layout ID"

### PR DESCRIPTION
**Pull request by dsn5ft**
Reverts material-components/material-components-android#2237

### CODE REVIEW

**Comment by AndrazP** [comment]
Hi @dsn5ft,
May I ask why was this reverted? Do you plan to include it in the next 1.6 release?

**Comment by drchen** [comment]
There was something wrong in our merging process. Will try to merge it again.

**Comment by 4brunu** [comment]
Hi @dsn5ft and @drchen any news in merging this again?
In case it helps, I opened https://github.com/material-components/material-components-android/pull/2525 that makes it easy to merge again.
Thanks

**Comment by drchen** [comment]
Hi, sorry for the late response. I noticed that you updated the source compatibility to Java 8 after the change had been approved. Unfortunately I'm not sure if we can do that now - it will force all of our clients to update their source compatibility as well. We will need a more thorough plan on this.

**Pull request merged**
