### PR TITLE
Save bottom sheet state on config change

### PR DESCRIPTION
**Pull request by SUPERCILEX**
See https://android-review.googlesource.com/c/platform/frameworks/support/+/593733

### CODE REVIEW

**Comment by yaraki** [comment]
@tec27 Hi, Travis. The CI seems to be failing due to some configuration error. Can you please take a look?

**Comment by SUPERCILEX** [comment]
@yaraki thanks for pointing me in the right direction! @tec27 see #54, it looks like the Gradle modules aren't setup correctly so all the packages are wrong and nothing compiles.

**Comment by SUPERCILEX** [comment]
@dsn5ft Can you take a look?

**Comment by dsn5ft** [comment]
Hi @SUPERCILEX, we have submitted this change internally and it will be included in an upcoming release, as well as synced here to GitHub. Thank you!

**Comment by SUPERCILEX** [comment]
SGTM

**Pull request closed without merging**
