### PR TITLE
[BottomNavigationView] Add selectMenuItem action to BottomNavigationView

### LINKED ISSUE #20: Enhancement - Add selected menu item to BottomNavigationView
### Overview

In the BottomNavigationView, there is no method to explicitly select a menu item.

Sometimes we need to move to another menu item when some action is done, is like moving to a particular tab like using ViewPager and TabLayout.

It also helps to click on a tab when doing espresso tests.

I worked on a PR to add this.

### PR DESCRIPTION
**Pull request by jotaemepereira**
Close #20

### CODE REVIEW

**Comment by jotaemepereira** [comment]
I signed it!

**Comment by jestelle** [comment]
Thanks for the PR!  We're catching up from holidays and new year planning.  But we'll be giving this more attention soon!

**Comment by jotaemepereira** [comment]
@jestelle What are you going to do with all the open PRs? We did not have any news since January. Is it worth continuing with this and resolving conflicts?

**Comment by ymarian** [comment]
This is supported now with BottomNavigationView#setSelectedItemId

**Pull request closed without merging**
