### PR TITLE
[Badge] Add text support

### PR DESCRIPTION
**Pull request by pubiqq**
Resolves https://github.com/material-components/material-components-android/issues/1217

### CODE REVIEW

**Comment by fsgjlp** [comment]
It's been 2 months since the pull request. When will it be added to the library?

**Comment by pubiqq** [comment]
bump

**Comment by pubiqq** [comment]
bump

**Comment by pubiqq** [comment]
bump

**Comment by pubiqq** [comment]
bump

**Comment by akhbulatov** [comment]
> It's been 2 months since the pull request. When will it be added to the library?

If a PR has a label "Await Design Feedback", you can forget about it for a couple of years

**Comment by pubiqq** [comment]
@pekingme, mb any news?

**Comment by pubiqq** [comment]
@pekingme, mb any news?

**Comment by pubiqq** [comment]
bump

**Comment by imhappi** [comment]
Thanks for the PR! Just wanted to give the update that text support for badges has been approved by design, but the specifications are not yet clear.

Will review and make some tweaks according to design specifications, and merge soon hopefully 👍

**Pull request closed without merging**
