### PR TITLE
[BottomSheetBehavior] Fix halfExpandedOffset calculation

### PR DESCRIPTION
**Pull request by ricknout**
This fixes the calculation of the half-expanded size of a Bottom Sheet when using the new `halfExpandedRatio` attribute. It also adds support for this in the catalog Bottom Sheet demo.

No related GitHub issue, but please see: https://issuetracker.google.com/issues/129457530

#### Don't forget:

- [x] Identify the component the PR relates to in brackets in the title.
  `[Buttons] Updated documentation`
- [x] Link to GitHub issues it solves. `closes #1234`
- [x] Sign the CLA bot. You can do this once the pull request is opened.

[Contributing](https://github.com/material-components/material-components/blob/develop/CONTRIBUTING.md#pull-requests)
has more information and tips for a great pull request.

### CODE REVIEW

**Comment by melaniegoetz** [comment]
looks great! thank you for this contribution
just a few minor comments and this is good to go, would prefer not to add and subsequently remove changes in commits in the same PR.

**Comment by ricknout** [comment]
Hi @melaniegoetz, thanks for the feedback! I've dropped the 3 commits that added/removed changes in favor of a single commit for adding the halfExpandedOffset demo. Hope this is good to go now 👍

**Comment by melaniegoetz** [comment]
hey @ricknout everything looks awesome! good to go, the PR will be accepted and likely synced out this week

**Comment by ricknout** [comment]
Hey @melaniegoetz, I see these commits have been added to the repo. Can I close this PR?

**Pull request closed without merging**
