### PR TITLE
[Slider] Do not capture inflation parameters for reuse

### PR DESCRIPTION
**Pull request by pubiqq**
Fixes https://github.com/material-components/material-components-android/issues/1578

### CODE REVIEW

**Review by drchen — COMMENTED** [review]
It looks like there's no behavioral change (which is also funny..). Am I missing anything because you said it probably fixes an issue?

**Comment by pubiqq** [comment]
I was just able to reproduce https://github.com/material-components/material-components-android/issues/1578 with [this example](https://github.com/material-components/material-components-android/issues/1578#issuecomment-1209048542). And yes, it looks like the PR really resolves the issue.

**Comment by drchen** [comment]
That's pretty bizarre to me... can you explain why the behavior can be different?

**Comment by pubiqq** [comment]
`attrs` is not just an `AttributeSet`, it's an `XmlResourceParser`. And when view inflation completes, the parser closes, and you can no longer get values from it. In other words, trying to preserve `attrs` is useless, after inflation it will not give correct values.

**Comment by drchen** [comment]
Interesting! That makes sense. : )

**Review by drchen — APPROVED** [review]

**Pull request closed without merging**
