### PR TITLE
[Snackbar] Fix the snackbar position when the anchor view layout listener is enabled

### PR DESCRIPTION
**Pull request by pubiqq**
Fixes https://github.com/material-components/material-components-android/issues/3194

### CODE REVIEW

**Comment by drchen** [comment]
Hi, thanks for the PR. I actually have a fix using a different approach on its way. : )

Let's pause the review here and see if my fix works.

**Comment by pubiqq** [comment]
Okay, no problem. 

P. S. If your solution is similar to this:

<details>
  <summary>Code</summary>
  
```java
private boolean extraBottomMarginAnchorViewChanged;

// ...

private void recalculateAndUpdateMargins() {
  int newBottomMarginAnchorView = calculateBottomMarginForAnchorView();
  if (newBottomMarginAnchorView != extraBottomMarginAnchorView) {
    extraBottomMarginAnchorViewChanged = true;
    extraBottomMarginAnchorView = newBottomMarginAnchorView;
  }

  if (extraBottomMarginAnchorViewChanged) {
    updateMargins();
  }
}

// ...

private void updateMargins() {
  // ...
  
  marginParams.bottomMargin = view.originalMargins.bottom + extraBottomMargin;
  marginParams.leftMargin = view.originalMargins.left + extraLeftMarginWindowInset;
  marginParams.rightMargin = view.originalMargins.right + extraRightMarginWindowInset;
  marginParams.topMargin = view.originalMargins.top;
  
  view.requestLayout();

  extraBottomMarginAnchorViewChanged = false;
  
  // ...
}
```
  
</details>

then I would still recommend taking mine.

**Comment by drchen** [comment]
Not really. But you reminded me a very good point regarding the originalMargins can also be changed. : )

**Comment by drchen** [comment]
Ah - actually. After re-reading it, I think your fix is better than mine. : )

Let me pull your PR for internal review instead.

**Review by drchen — APPROVED** [review]

**Comment by pubiqq** [comment]
Oh, I almost forgot: this change slightly aggravates the existing problem with `gestureInsetBottomIgnored`, but I intentionally did nothing about it, because in the next PR I'm going to eliminate the problem completely.
However, if you really need to, I can also add a regression fix (only regression, not the whole problem) to this PR.

**Comment by drchen** [comment]
Ah. Yes please, a quick workaround for now will be good. Just FYI any regression may cause a lot of internal breakages that make the change hard to land itself. : )   (I do see some but haven't got time to check yet. So if you already have some idea that will be very helpful.)

**Comment by pubiqq** [comment]
I believe this is not the case. However, ok, I can fix the issue in another way.

**Comment by pubiqq** [comment]
I believe this is not the case. But ok, I can fix the issue in another way.

**Pull request closed without merging**
